In [4]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,roc_auc_score,roc_curve
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df=pd.read_csv('diabetes.csv')

In [6]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

- **Naive Bias always tries to consider independent features**

In [7]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
x=df.drop('Outcome',axis=1)
y=df['Outcome']

In [12]:
c=x.columns

In [13]:
sc=StandardScaler()
x=sc.fit_transform(x)

In [14]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [15]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.2,random_state=77)

In [16]:
xtrain

array([[ 0.93691372,  0.97351238,  0.97680475, ...,  2.2854884 ,
        -0.40734244,  0.23476686],
       [-0.84488505, -0.184482  ,  0.04624525, ...,  0.33093202,
         0.17252035, -0.10558415],
       [ 2.12477957,  0.19108374,  1.90736425, ...,  0.8893767 ,
        -0.85129988,  1.51108316],
       ...,
       [-1.14185152, -1.68674498,  0.35643175, ...,  1.68896794,
        -0.83921941,  1.08564439],
       [-0.84488505, -0.90431634, -0.36733675, ..., -1.58554859,
         0.03057477, -0.70119842],
       [-1.14185152,  0.62924378,  0.77001375, ...,  0.05170968,
        -0.11741105, -0.95646168]])

In [18]:
nb=GaussianNB()

In [19]:
nb.fit(xtrain,ytrain)

GaussianNB()

In [20]:
nb.score(xtest,ytest)

0.7402597402597403

In [21]:
nb.score(xtrain,ytrain)

0.755700325732899

### <font color='clue'> If we are using Naive Bias then are we supposed to use Naiva Bias</font>

No, we are not supposed to use as in PCA it will try to take a component of all the axis and try to re create its data in a new axis so in that it won't be able to retain its independent relationships with y values.<br>
And Naiva Bias says if we have direct relationship between features and labels and if feature is independently going to affect our label so we should be using Naiva Bias

In [25]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [26]:
from statsmodels.stats.outliers_influence import variance_inflation_factor 
vif = pd.DataFrame()
vif["vif"] = [variance_inflation_factor(x,i) for i in range(x.shape[1])]
vif["Features"] = c

#let's check the values
vif

vif                  Features
0  1.430872               Pregnancies
1  1.298961                   Glucose
2  1.181863             BloodPressure
3  1.507432             SkinThickness
4  1.427536                   Insulin
5  1.297450                       BMI
6  1.067090  DiabetesPedigreeFunction
7  1.588368                       Age

- **So its very very low**